import UnselectedWorkspace from 'icons/workspace/unselected'
import SelectedWorkspace from 'icons/workspace/selected'
import DropArrow from 'icons/arrow/drop'
import RangeArrow from 'icons/arrow/range'
import UpwardArrow from 'icons/arrow/upward'
import DoubleArrow from 'icons/arrow/double'
import Arrow from 'icons/arrow/arrowLine'
import SuccessAlert from 'icons/alert/success'
import WarningAlert from 'icons/alert/warning'
import ErrorAlert from 'icons/alert/error'
import InfoAlert from 'icons/alert/info'
import GroupUser from 'icons/user/group'
import FillUSer from 'icons/user/fill'
import OutlinedUser from 'icons/user/outlined'

import Calendar from 'icons/calendar'
import Catalogue from 'icons/catalogue'
import Chart from 'icons/chart'
import Cloud from 'icons/cloud'
import Download from 'icons/download'
import Edit from 'icons/edit'
import Erase from 'icons/erase'
import Graph from 'icons/graph'
import Light from 'icons/light'
import LockOpen from 'icons/lockOpen'
import Menu from 'icons/menu'
import Plus from 'icons/plus'
import Store from 'icons/store'
import Support from 'icons/support'
import Close from 'icons/close'
import Dark from 'icons/dark'
import Favorite from 'icons/favorite'
import Home from 'icons/home'
import Logout from 'icons/logout'
import Notification from 'icons/notification'
import Options from 'icons/options'
import Settings from 'icons/settings'
import Visibility from 'icons/visibility'
import VisibilityOff from 'icons/visibilityOff'
import Badges from 'icons/badges'
import CheckCircle from 'icons/checkCircle'
import Language from 'icons/language'
import Label from 'icons/label'
import Search from 'icons/search'
import SearchOff from 'icons/search/off'
import Camera from 'icons/camera'
import Eye from 'icons/eye'
import Color from 'icons/color'
import Drag from 'icons/drag'
import Delete from 'icons/deleteIcon'
import File from 'icons/file'
import Folder from 'icons/folder'
import Location from 'icons/location'
import Mail from 'icons/mail'
import Money from 'icons/money'
import More from 'icons/more'
import Pin from 'icons/pin'
import Print from 'icons/print'
import Product from 'icons/product'
import Robot from 'icons/robot'
import Supermarket from 'icons/supermarket'
import Update from 'icons/update'
import Upload from 'icons/upload'

export { UnselectedWorkspace }
export { SelectedWorkspace }

//arrow
export { DropArrow }
export { RangeArrow }
export { UpwardArrow }
export { DoubleArrow }
export { Arrow }

//alerts
export { SuccessAlert }
export { WarningAlert }
export { ErrorAlert }
export { InfoAlert }

//user
export { GroupUser }
export { FillUSer }
export { OutlinedUser }

//General
export { Calendar }
export { Catalogue }
export { Chart }
export { Cloud }
export { Download }
export { Edit }
export { Erase }
export { Graph }
export { Light }
export { LockOpen }
export { Menu }
export { Plus }
export { Store }
export { Support }
export { Close }
export { Dark }
export { Favorite }
export { Home }
export { Logout }
export { Notification }
export { Options }
export { Settings }
export { Visibility }
export { VisibilityOff }
export { Badges }
export { CheckCircle }
export { Language }
export { Label }
export { Search }
export { SearchOff }
export { Camera }
export { Eye }
export { Color }
export { Drag }
export { Delete }
export { File }
export { Folder }
export { Location }
export { Money }
export { More }
export { Pin }
export { Print }
export { Product }
export { Robot }
export { Supermarket }
export { Update }
export { Upload }
